### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aays** [bigdatachallenge/bigdatachallenge.github.io#1]
Intro
* [x] Actual descriptive text
* [ ] Brief description of SF itself
* [x] Sponsor logos
* [ ] Fix background image
* [x] Add link to tickets

Schedule
* [x] Orientation day schedule - with location
* [x] Overall workshop schedule
* [ ] Final day schedule + IBM location

FAQ
* [x] Fill this in

Contact
* [x] Fill in with relevant SF emails + links to Facebook page
